### ISSUE TITLE
Can the scoped_key_salt be public?

### ISSUE THREAD

**Issue by vladikoff** [warner/fxa-scoped-keys-review#1]
Hey @warner,

Per doc

> scoped_key_salt: a 32-byte string of additional entropy specific to this scoped key, which we can use to manage key rotation on a per-scope basis.

Should we keep that salt a secret or can it be public?

**Comment by warner** [comment]
It should be kept secret. Specifically: someone who successfully logs in at time T, then gets kicked out because of a key-rotation, should not be able to derive the new (post-rotation) key. If `scoped_key_salt` is public, then their previous (irrevocable) knowledge of `kB` combined with the new `scoped_key_salt` would give them access to future derived keys, which violates the goal of rotating keys.

The current value should only be revealed to clients who prove control over the account (specifically knowledge of the class-B key, by virtue of making it through the login process).

Because of that, `scoped_key_salt` should probably get a different name. "salt" implies a unique-but-public value, available to anyone who can name the account they want to use (the onepw `authSalt` isn't exposed that way, but it could technically be exposed safely, as long as `verifyhash` wasn't also exposed).

"epoch" or "rotation" might be useful nouns. `scoped_epoch_access_key`? Might need some jargon-refactoring to make that work.

**Comment by rfk** [comment]
Thanks @warner, that's really helpful for clarifying the role of the "salt" here.

For the sake of simplicity, I would like us to start with each scope having an initial `scoped_key_salt` of all zeros, to reduce the number of secrets we have to manage on the backend while we're rolling this out.  But if and when we need to do a key-rotation for a particular scope, we can create a new value and keep it secret as you describe above.

Does this seem reasonable?  It seems in-bounds to me because we only depend on it being secret after a rotation event.

> scoped_key_salt should probably get a different name. "salt" implies a unique-but-public value,
> available to anyone who can name the account they want to use

This is a great point; I'll have to sleep on what a good name might be though :-)

I'd also be interested in whether this ability to do key rotations on a scope-by-scope basis seems useful, as opposed to e.g. just rotating the underlying kB.  And if it does, should we try to figure out how to implement a similar rotation mechanism just for the sync keys, which currently have no such thing?

In particular:

> someone who successfully logs in at time T, then gets kicked out because of a key-rotation, should
> not be able to derive the new (post-rotation) key. If scoped_key_salt is public, then their previous
> (irrevocable) knowledge of kB combined with the new scoped_key_salt would give them access to
> future derived keys

It's not clear to me whether rotating the scoped keys is the right way to deal with such a situation.  If we're trying to kick out such a user, we should rotate kB itself rather than the things derived from kB.

The key rotation events we had in mind here, were more along the lines of a breach of a relying application that exposed access tokens and scoped keys, but did not reveal the underlying kB (because we didn't have to hand that to the relying application in the first place, thanks to this "scoped keys" business).

OTOH, keeping them secret should be pretty straightforward so we should probably just do so anyway :-)
